"""Port for persistence of user-visible long-running operations."""

from __future__ import annotations

from typing import Protocol, Sequence

from ...domain.operations import Operation, OperationDraft, OperationItem, OperationItemDraft, OperationItemStatus, OperationStatus


class OperationRepository(Protocol):
    """Stores and retrieves operation state without choosing a database."""

    def create(self, draft: OperationDraft, items: Sequence[OperationItemDraft] = ()) -> Operation: ...

    def create_idempotent(self, draft: OperationDraft, items: Sequence[OperationItemDraft], idempotency_key: str, fingerprint: str) -> tuple[Operation, bool]: ...

    def add_items(self, operation_id: str, items: Sequence[OperationItemDraft]) -> Operation: ...

    def get(self, operation_id: str) -> Operation | None: ...

    def items_for(self, operation_id: str) -> list[OperationItem]: ...

    def transition(self, operation_id: str, status: OperationStatus, *, stage: str | None = None, expected_version: int | None = None) -> Operation: ...

    def set_stage(self, operation_id: str, stage: str, *, expected_version: int | None = None) -> Operation: ...

    def transition_item(self, item_id: str, status: OperationItemStatus, *, stage: str | None = None, error_code: str | None = None, result: dict | None = None) -> OperationItem: ...

    def cancel_pending_items(self, operation_id: str) -> list[OperationItem]: ...

    def unfinished(self) -> list[Operation]: ...

    def list(self, *, statuses: Sequence[OperationStatus] = (), operation_type: str | None = None, created_from: str | None = None, created_to: str | None = None, has_errors: bool | None = None, limit: int = 50, offset: int = 0) -> tuple[list[Operation], int]: ...

    def items_page(self, operation_id: str, *, limit: int = 100, offset: int = 0) -> tuple[list[OperationItem], int]: ...
