"""Port for exclusive locks over mutable canonical resources."""

from typing import Iterable, Protocol

from ...domain.locks import LockAcquireResult, ResourceLock, ResourceLockRequest


class ResourceLockRepository(Protocol):
    def acquire(self, owner_operation_id: str, resources: Iterable[ResourceLockRequest], *, ttl_seconds: int = 60) -> LockAcquireResult: ...
    def heartbeat(self, lock: ResourceLock, *, ttl_seconds: int = 60) -> bool: ...
    def release(self, lock: ResourceLock) -> bool: ...
    def release_operation(self, owner_operation_id: str) -> int: ...
    def owns(self, lock: ResourceLock) -> bool: ...
